server:
  servlet:
    context-path: /smart-estoque
  port: 3000
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb+srv://alexandreoliveirajnrestudos:q6pHF5Ug8d2yjob3@cluster0.ra0atsp.mongodb.net/?retryWrites=true&w=majority
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
